s = Stimulus(1e4, 2200, 'triangular', 20e-3, 2e-3, 80e-3, 3);
[stim, times, trigs] = s.generateStimulus(1.0, 50, 6);

disp("Afferent");
afferent = {};
afferent.neuron = Neuron(14e-12, 0.5e9, -65e-3, -30e-3, -100e-3, -55e-3, -20e-3, 0.02);
afferent.excitatorySynapse = Synapse(1e-9, 0.01);
afferent.excitation = afferent.excitatorySynapse.call(trigs, s.fs, 0, 0, 0.01);
afferent.inhibitorySynapse = Synapse(0e-9, 0.01);
afferent.inhibition = afferent.inhibitorySynapse.call(trigs, s.fs, 0, 0, 0.01);
[afferent.response, afferent.spkTrigs] = afferent.neuron.call(0e-9, afferent.excitation, afferent.inhibition, s.fs);

disp("Relay");
relayNeuron = {};
relayNeuron.neuron = Neuron(14e-12, 0.5e9, -65e-3, -30e-3, -100e-3, -55e-3, -20e-3, 0.02);
relayNeuron.excitatorySynapse = Synapse(1e-9, 0.01);
relayNeuron.excitation = relayNeuron.excitatorySynapse.call(afferent.spkTrigs, s.fs, 0, 0, 0.01);
relayNeuron.inhibitorySynapse = Synapse(0e-9, 0.01);
relayNeuron.inhibition = relayNeuron.inhibitorySynapse.call(afferent.spkTrigs, s.fs, 0, 0, 0.01);
[relayNeuron.response, relayNeuron.spkTrigs] = relayNeuron.neuron.call(0e-9, relayNeuron.excitation, relayNeuron.inhibition, s.fs);

disp("LIN");
lin = {};
lin.neuron = Neuron(14e-12, 0.5e9, -65e-3, -30e-3, -100e-3, -57e-3, -20e-3, 0.03);
lin.excitatorySynapse = Synapse(1e-9, 0.03);
lin.excitation = lin.excitatorySynapse.call(trigs, s.fs, 1/30, 0.03, 0.035);
lin.inhibitorySynapse = Synapse(0.8e-9, 0.01);
lin.inhibition = lin.inhibitorySynapse.call(relayNeuron.spkTrigs, s.fs, 1/30, 0.08, 0.01);
[lin.response, lin.spkTrigs] = lin.neuron.call(0e-9, lin.excitation, lin.inhibition, s.fs);

disp("ICN");
icn = {};
icn.neuron = Neuron(14e-12, 0.5e9, -65e-3, -30e-3, -100e-3, -57e-3, -20e-3, 0.03);
icn.excitatorySynapse = Synapse(0.6e-9, 0.02);
icn.excitation = icn.excitatorySynapse.call(trigs, s.fs, 1/30, 0.1, 0.055);
icn.inhibitorySynapse = Synapse(1e-9, 0.015);
icn.inhibition = icn.inhibitorySynapse.call(lin.spkTrigs, s.fs, 1/30, -0.05, 0.01);
[icn.response, icn.spkTrigs] = icn.neuron.call(0e-9, icn.excitation, icn.inhibition, s.fs);

disp("ICN: 2nd Order");
icn2 = {};
icn2.neuron = Neuron(14e-12, 0.5e9, -65e-3, -30e-3, -100e-3, -57e-3, -20e-3, 0.03);
icn2.excitatorySynapse = Synapse(1e-9, 0.01);
icn2.excitation = icn2.excitatorySynapse.call(icn.spkTrigs, s.fs, 1/30, 0.1, 0.0);
icn2.inhibitorySynapse = Synapse(0e-9, 0.015);
icn2.inhibition = icn2.inhibitorySynapse.call(trigs, s.fs, 1/30, -0.05, 0.01);
[icn2.response, icn2.spkTrigs] = icn2.neuron.call(0e-9, icn2.excitation, icn2.inhibition, s.fs);

figure();
tiledlayout(9, 1);
nexttile;
plot(times, icn2.response, 'k');
ylabel('2nd Order ICN');
nexttile;
plot(times, icn2.excitation, 'r', times, icn2.inhibition, 'b');
ylabel('2nd Order ICN conductances');
nexttile;
plot(times, icn.response, 'k');
ylabel('ICN response');
nexttile;
plot(times, icn.excitation, 'r', times, icn.inhibition, 'b');
ylabel('ICN conductances');
nexttile;
plot(times, lin.response, 'k');
ylabel('LIN response');
nexttile;
plot(times, lin.excitation, 'r', times, lin.inhibition, 'b');
ylabel('LIN conductances');
nexttile;
plot(times, relayNeuron.response, 'k');
ylabel('Relay neuron response');
nexttile;
plot(times, afferent.response, 'k');
ylabel('Afferent neuron response');
nexttile;
plot(times, stim, 'k');
ylabel('stimulus');
xlabel('time(sec)');
% linkaxes(ax, 'x');